{
 "title": "AWS App Mesh: Canary Releases",
 "tags": [ "flagger" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "flagger_canary_status" },
   { "name": "workload", "label": "Workload", "query": "flagger_canary_status" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>RED: $workload.$namespace</span>\n</div>"
  },
  {
   "title": "Primary: Incoming Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",app=~\"$workload-primary\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",app=~\"$workload-primary\",envoy_response_code!~\"5.*\"}[30s])) / sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",app=~\"$workload-primary\"}[30s]))"
    }
   ]
  },
  {
   "title": "Canary: Incoming Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",app=~\"$workload\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",app=~\"$workload\",envoy_response_code!~\"5.*\"}[30s])) / sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",app=~\"$workload\"}[30s]))"
    }
   ]
  },
  {
   "title": "Primary: Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{kubernetes_namespace=~\"$namespace\",app=~\"$workload-primary\"}[30s])))",
     "legendFormat": "traffic"
    }
   ]
  },
  {
   "title": "Canary: Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{kubernetes_namespace=~\"$namespace\",app=~\"$workload\"}[30s])))",
     "legendFormat": "traffic"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>USE: $workload.$namespace</span>\n</div>"
  },
  {
   "title": "Primary: CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "CPU seconds / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"$namespace\",pod_name=~\"$workload-primary.*\", container_name!~\"POD|istio-proxy|envoy\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Canary: CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "CPU seconds / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"$namespace\",pod_name=~\"$workload.*\", pod_name!~\"$workload-primary.*\", container_name!~\"POD|istio-proxy|evnoy\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Primary: Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=~\"$workload-primary.*\", container_name!~\"POD|istio-proxy|envoy\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Canary: Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=~\"$workload.*\", pod_name!~\"$workload-primary.*\", container_name!~\"POD|istio-proxy|envoy\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Primary: Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$workload-primary.*\"}[1m])) ",
     "legendFormat": "received"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$workload-primary.*\"}[1m]))",
     "legendFormat": "transmited"
    }
   ]
  },
  {
   "title": "Canary: Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$workload.*\",pod_name!~\"$workload-primary.*\"}[1m])) ",
     "legendFormat": "received"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$workload.*\",pod_name!~\"$workload-primary.*\"}[1m]))",
     "legendFormat": "transmited"
    }
   ]
  }
 ]
}
{
 "title": "AWS App Mesh: Control Plane",
 "description": "AWS App Mesh control plane overview",
 "tags": [ "appmesh" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "AWS SDK API calls",
   "type": "graph",
   "description": "Total number of SDK API calls from App Mesh controller to AWS",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_api_calls_total[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "AWS API calls 2xx response",
   "type": "graph",
   "description": "Successful AWS API calls with 2xx response ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_api_calls_total{status_code=~\"2.*\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "AWS API calls 4xx/5xx response",
   "type": "graph",
   "description": "Failed AWS API calls with 4xx/5xx response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_api_calls_total{status_code=~\"4.*|5.*\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of goroutines for the App Mesh controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"appmesh-system\", control_plane=\"appmesh-controller\"}",
     "legendFormat": "appmesh-controller"
    }
   ]
  },
  {
   "title": "Work queue unfinished work",
   "type": "graph",
   "description": "How many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_unfinished_work_seconds{kubernetes_namespace=\"appmesh-system\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "appmesh-system namespace containers memory working set",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"appmesh-system\",container!=\"POD\",container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "appmesh-system namespace containers CPU usage seconds total",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"appmesh-system\",container!=\"POD\",container!=\"\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}
{
 "title": "AWS App Mesh: Data Plane",
 "description": "AWS App Mesh data plane overview",
 "tags": [ "appmesh" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Envoy Sidecars",
   "type": "singlestat",
   "description": "Total number of App Mesh sidecars",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_server_live{job=\"appmesh-envoy\"})",
     "legendFormat": "Total Envoy sidecars"
    }
   ]
  },
  {
   "title": "Unhealthy Sidecars  ",
   "type": "singlestat",
   "description": "Unhealthy App Mesh Envoy instances",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{job=\"appmesh-envoy\"})  - sum(envoy_cluster_membership_healthy{job=\"appmesh-envoy\"}))",
     "legendFormat": "Unhealthy sidecars"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "App Mesh sidecars total inbound connections",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{job=\"appmesh-envoy\"})",
     "legendFormat": "Total connections"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "description": "App Mesh in/out traffic",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{job=\"appmesh-envoy\"}[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{job=\"appmesh-envoy\"}[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Envoy Requests by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy requests per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Envoy 2xx Requests by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy success HTTP requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\",envoy_response_code=~\"2.*\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}} 5xx"
    }
   ]
  },
  {
   "title": "Envoy 5xx/4xx Requests by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy failed HTTP requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\",envoy_response_code=~\"5.*\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}} 5xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{job=\"appmesh-envoy\",envoy_response_code=~\"4.*\"}[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}} 4xx"
    }
   ]
  },
  {
   "title": "Envoy Memory Usage by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy sidecar containers memory working set by namespace",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"envoy\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Envoy CPU Usage by Namespace",
   "type": "graph",
   "description": "App Mesh Envoy sidecar containers CPU usage seconds total",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container=\"envoy\"}[1m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Connection Timeout by Namespace",
   "type": "graph",
   "description": "Total connection connect timeouts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Request Timeout by Namespace",
   "type": "graph",
   "description": "Total requests that timed out waiting for a response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Number of enforced outlier ejections",
   "type": "graph",
   "description": "Number of enforced outlier ejections due to any outlier type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(envoy_cluster_outlier_detection_ejections_enforced_total{job=\"appmesh-envoy\"}[1m]))) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Number of currently ejected hosts",
   "type": "graph",
   "description": "Number of currently ejected hosts due to outlier detection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{job=\"appmesh-envoy\"}) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Number of enforced consecutive 5xx ejections",
   "type": "graph",
   "description": "Number of enforced consecutive 5xx ejections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(envoy_cluster_outlier_detection_ejections_enforced_consecutive_5xx{job=\"appmesh-envoy\"}[1m]))) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Number of detected consecutive 5xx ejections",
   "type": "graph",
   "description": "Number of detected consecutive 5xx ejections (even if unenforced)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx{job=\"appmesh-envoy\"}[1m]))) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Connection(cx) circuit breakers",
   "type": "graph",
   "description": "Number of connection circuit breakers for a namespace. Envoy metric: cx_open",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_circuit_breakers_default_cx_open) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Requests (rq) circuit breakers",
   "type": "graph",
   "description": "Number of request circuit breakers for a namespace. Envoy metric: rq_open",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_circuit_breakers_default_rq_open) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Successful TLS connections",
   "type": "graph",
   "description": "Total successful TLS connection handshakes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_handshake[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL Failures - Missing Client Cert",
   "type": "graph",
   "description": "Total TLS connections that failed because of missing client certificate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_no_cert[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL - SAN Verification Failures",
   "type": "graph",
   "description": "Total TLS connections that failed SAN verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_san[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL - CA Verification Failures",
   "type": "graph",
   "description": "Total TLS connections that failed CA verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_error[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL Connection errors",
   "type": "graph",
   "description": "Total TLS connection errors not including failed certificate verifications",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_connection_error[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Successful TLS connections",
   "type": "graph",
   "description": "Total successful TLS connection handshakes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_handshake[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL Failures - Missing Client Cert",
   "type": "graph",
   "description": "Total TLS connections that failed because of missing client certificate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_no_cert[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL - SAN Verification Failures",
   "type": "graph",
   "description": "Total TLS connections that failed SAN verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_san[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL - CA Verification Failures",
   "type": "graph",
   "description": "Total TLS connections that failed CA verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_fail_verify_error[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "SSL Connection errors",
   "type": "graph",
   "description": "Total TLS connection errors not including failed certificate verifications",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_connection_error[1m])) by (kubernetes_namespace)",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  }
 ]
}